# Generated by Django 5.1.3 on 2024-12-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='post',
            field=models.FileField(blank=True, null=True, upload_to='announcements/'),
        ),
    ]
