# Generated by Django 5.1.3 on 2024-12-11 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_notice_delete_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='is_published',
        ),
    ]
