# Generated by Django 5.1.3 on 2024-12-11 00:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_remove_notice_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
