# Generated by Django 5.1.3 on 2024-12-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_notice_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
