# Generated by Django 5.1.3 on 2025-01-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0006_alter_notice_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
