# Generated by Django 5.1.3 on 2024-11-18 15:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComputerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('computer_type', models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('Tablet', 'Tablet'), ('Server', 'Server'), ('Other', 'Other')], default='Desktop', max_length=10)),
                ('processor', models.CharField(blank=True, help_text='In GHz(e.g.:i5 2.9 GHz)', max_length=25, null=True)),
                ('ram', models.CharField(blank=True, help_text='GB', max_length=3, null=True)),
                ('hdd', models.CharField(help_text='GB/TB', max_length=3, verbose_name='HDD/Storage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='computer_model_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='computer_model_updated_by', to=settings.AUTH_USER_MODEL)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='computer_models', to='computers.maker')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_project', models.BooleanField(default=False)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty_info', models.CharField(default='N/A', max_length=100, verbose_name='Warranty')),
                ('computer_name', models.CharField(blank=True, default='MCWT', max_length=100, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Obsolete', 'Obsolete'), ('In Storage', 'In Storage'), ('Faulty', 'Faulty'), ('Donated', 'Donated'), ('Lost', 'Lost'), ('Other', 'Other')], default='Active', max_length=12)),
                ('date_received', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_installed', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='system_audit/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='computer_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='computer_updated_by', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='computers', to='computers.computermodel')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
