# Generated by Django 5.1.3 on 2024-11-18 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_alter_computermodel_processor'),
        ('users', '0003_department_location_user_department_user_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='computer_departments', to='users.department'),
        ),
        migrations.AddField(
            model_name='computer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='computer_locations', to='users.location'),
        ),
        migrations.AddField(
            model_name='computer',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Operating System'),
        ),
        migrations.AddField(
            model_name='computer',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='computer_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
