# Generated by Django 5.1.3 on 2024-11-28 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='microsoftofficeinstalled',
            old_name='comments',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='microsoftofficeinstalled',
            name='has_failed',
        ),
    ]
