# Generated by Django 5.1.3 on 2024-11-28 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0003_rename_comments_microsoftofficeinstalled_notes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MicrosoftOfficeInstalled',
        ),
    ]
