# Generated by Django 5.1.3 on 2024-11-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0003_computer_department_computer_location_computer_os_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='os',
            field=models.CharField(blank=True, choices=[('Windows 10', 'Windows 10'), ('Windows 11', 'Windows 11'), ('Windows 7', 'Windows 7'), ('Windows 8', 'Windows 8'), ('Windows 8.1', 'Windows 8.1'), ('Windows Server 2022', 'Windows Server 2022'), ('Other', 'Other')], default='Windows 10', max_length=100, null=True, verbose_name='Operating System'),
        ),
    ]
