# Generated by Django 5.1.3 on 2024-11-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0004_alter_computer_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='computermodel',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='date_installed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Obsolete', 'Obsolete'), ('In Storage', 'In Storage'), ('Faulty', 'Faulty'), ('Donated', 'Donated'), ('Lost', 'Lost'), ('Other', 'Other')], default='In Storage', max_length=12),
        ),
    ]
