# Generated by Django 5.1.3 on 2024-11-28 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0007_microsoftoffice_computers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='microsoftoffice',
            name='assigned_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='microsoftoffice',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ms_office_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
