# Generated by Django 5.1.3 on 2024-11-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0007_alter_computer_os_alter_computermodel_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computermodel',
            name='hdd',
            field=models.CharField(help_text='GB/TB', max_length=5, verbose_name='HDD/Storage'),
        ),
    ]
