# Generated by Django 5.1.3 on 2024-11-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0008_alter_computermodel_hdd'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
