# Generated by Django 5.1.3 on 2024-11-28 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0008_microsoftoffice_assigned_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftOfficeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('date_assigned', models.DateTimeField()),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_key_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('computers', models.ManyToManyField(related_name='office_key_computers', to='computers.computer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_key_created_by', to=settings.AUTH_USER_MODEL)),
                ('microsoft_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='computers.microsoftoffice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_key_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
