# Generated by Django 5.1.3 on 2024-11-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0009_computer_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['name'], 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AddField(
            model_name='status',
            name='colour',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
