# Generated by Django 5.1.3 on 2024-11-28 23:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0009_microsoftofficeassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microsoftofficeassignment',
            name='date_assigned',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
