# Generated by Django 5.1.3 on 2024-11-28 23:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0010_alter_microsoftofficeassignment_date_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microsoftofficeassignment',
            name='date_assigned',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
