# Generated by Django 5.1.3 on 2024-11-20 16:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0011_monitormodel_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='date_received',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
