# Generated by Django 5.1.3 on 2024-11-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0011_alter_microsoftofficeassignment_date_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microsoftofficeassignment',
            name='microsoft_office',
        ),
        migrations.RemoveField(
            model_name='microsoftofficeassignment',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='microsoftofficeassignment',
            name='computers',
        ),
        migrations.RemoveField(
            model_name='microsoftofficeassignment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='microsoftofficeassignment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='microsoftofficeversion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='microsoftofficeversion',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='MicrosoftOffice',
        ),
        migrations.DeleteModel(
            name='MicrosoftOfficeAssignment',
        ),
        migrations.DeleteModel(
            name='MicrosoftOfficeVersion',
        ),
    ]
