# Generated by Django 5.1.3 on 2024-11-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0012_alter_monitor_date_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitormodel',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
