# Generated by Django 5.1.3 on 2024-11-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0013_monitormodel_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='monitor',
            field=models.ManyToManyField(blank=True, related_name='monitors', to='computers.monitor'),
        ),
    ]
