# Generated by Django 5.1.3 on 2025-01-31 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0013_computercomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='image',
            new_name='file',
        ),
    ]
