# Generated by Django 5.1.3 on 2024-11-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0014_computer_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computermodel',
            name='computer_type',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('server', 'Server'), ('other', 'Other')], default='desktop', max_length=10),
        ),
    ]
