# Generated by Django 5.1.3 on 2024-11-21 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0015_alter_computermodel_computer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='computers', to='computers.computermodel'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='computer_status', to='computers.status'),
        ),
    ]
