# Generated by Django 5.1.3 on 2024-11-21 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0016_alter_computer_model_alter_computer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='computers', to='computers.computermodel'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='computer_status', to='computers.status'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='warranty_info',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True, verbose_name='Warranty'),
        ),
    ]
