# Generated by Django 5.1.3 on 2024-11-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0017_alter_computer_model_alter_computer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computermodel',
            name='processor',
            field=models.CharField(blank=True, help_text='In GHz(e.g.:i5 2.9 GHz)', max_length=100, null=True),
        ),
    ]
