# Generated by Django 5.1.3 on 2024-11-27 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0020_microsoftofficekey_delete_microsoftoffice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_key', models.CharField(max_length=30, unique=True)),
                ('date_installed', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('is_installed', models.BooleanField(default=False)),
                ('has_failed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('computer', models.ForeignKey(blank=True, help_text='serial number', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_installations', to='computers.computer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ms_office_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ms_office_updated_by', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='computers.microsoftofficeversion')),
            ],
            options={
                'ordering': ['-date_installed'],
            },
        ),
        migrations.DeleteModel(
            name='MicrosoftOfficeKey',
        ),
    ]
