# Generated by Django 5.1.3 on 2024-11-27 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0021_microsoftoffice_delete_microsoftofficekey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='microsoftoffice',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='microsoftoffice',
            name='has_failed',
        ),
        migrations.RemoveField(
            model_name='microsoftoffice',
            name='is_installed',
        ),
        migrations.CreateModel(
            name='MicrosoftOfficeInstalled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_installed', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('has_failed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('computer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_installed', to='computers.computer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_installed_created_by', to=settings.AUTH_USER_MODEL)),
                ('microsoft_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installed_office', to='computers.microsoftoffice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_installed_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
