# Generated by Django 5.1.3 on 2024-11-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officekeys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microsoftoffice',
            name='product_key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='microsoftofficeversion',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
