[project]
name = "dipt-equipment-inventory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crispy-bootstrap5>=2024.10",
    "django>=5.1.3",
    "markdown>=3.7",
    "python-dotenv>=1.0.1",
    "six>=1.16.0",
]
