# Generated by Django 5.1.3 on 2024-11-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('clerk', 'Clerk'), ('technician', 'Technician'), ('manager', 'Manager'), ('user', 'User')], default='user', max_length=100),
        ),
    ]
