# Generated by Django 5.1.3 on 2025-01-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_admin_user_is_manager_user_is_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tech',
            field=models.BooleanField(default=False),
        ),
    ]
