# Generated by Django 5.1.3 on 2025-01-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_roles_user_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_role',
            new_name='user_roles',
        ),
    ]
