# Generated by Django 5.1.3 on 2025-01-23 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_user_role_user_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_roles',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
