# Generated by Django 5.1.3 on 2024-11-28 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('computers', '0002_initial'),
        ('printers', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printer_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='printer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printer_departments', to='users.department'),
        ),
        migrations.AddField(
            model_name='printer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printer_locations', to='users.location'),
        ),
        migrations.AddField(
            model_name='printer',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.status'),
        ),
        migrations.AddField(
            model_name='printer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printer_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='printermodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printer_model_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='printermodel',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.maker'),
        ),
        migrations.AddField(
            model_name='printermodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printer_model_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='printer',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='printers.printermodel'),
        ),
    ]
