# Generated by Django 5.1.3 on 2024-11-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0002_printer_slug_printermodel_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printer',
            options={'ordering': ['-ip_addr']},
        ),
    ]
