# Generated by Django 5.1.3 on 2025-01-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0003_printercomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printer',
            old_name='printer_name',
            new_name='name',
        ),
    ]
