# Generated by Django 5.1.3 on 2024-11-27 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0003_alter_printer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='date_received',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
