# Generated by Django 5.1.3 on 2025-01-24 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0004_rename_printer_name_printer_name'),
        ('users', '0008_remove_user_user_roles_delete_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='printercomment',
            old_name='printer',
            new_name='device',
        ),
        migrations.AlterField(
            model_name='printer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='printer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_departments', to='users.department'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_locations', to='users.location'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='printers.printermodel'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='printercomment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_comment_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='printercomment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_comment_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='printermodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_model_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='printermodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='device_models/'),
        ),
        migrations.AlterField(
            model_name='printermodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_model_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
