# Generated by Django 5.1.3 on 2025-02-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='knowledge_base/'),
        ),
    ]
