# Generated by Django 5.1.3 on 2024-11-22 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_closed',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(default='dhg9Alxt', editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ManyToManyField(related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
