# Generated by Django 5.1.3 on 2024-12-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_closed_at_ticket_closed_by_ticket_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_category',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_category',
            field=models.ManyToManyField(to='tickets.ticketcategory', verbose_name='category'),
        ),
    ]
