# Generated by Django 5.1.3 on 2024-12-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_ticket_ticket_category_ticket_ticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='tickets.ticketcategory'),
        ),
    ]
