# Generated by Django 5.1.3 on 2024-12-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_category',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_category',
            field=models.ManyToManyField(to='tickets.ticketcategory', verbose_name='categories'),
        ),
    ]
