# Generated by Django 5.1.3 on 2024-11-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_ticket_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(default='4QvuXBBo', editable=False, max_length=8, unique=True),
        ),
    ]
