# Generated by Django 5.1.3 on 2024-11-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_alter_ticket_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(default='u7TsLn3S', editable=False, max_length=8, unique=True),
        ),
    ]
