# Generated by Django 5.1.3 on 2024-11-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0060_alter_ticket_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(default='C4K1jogh', editable=False, max_length=8, unique=True),
        ),
    ]
