# Generated by Django 5.1.3 on 2024-12-10 19:43

import stocks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(default=stocks.models.generate_short_id, editable=False, max_length=8, null=True, unique=True),
        ),
    ]
