# Generated by Django 5.1.3 on 2024-12-11 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_item_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
    ]
