# Generated by Django 5.1.3 on 2025-01-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_item_updated_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
    ]
